name: Docs

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
    - name: Run markdownlint
      run: cd docs && markdownlint .
  build_book:
    runs-on: ubuntu-latest
    needs: markdownlint
    steps:
    - uses: actions/checkout@v4
    - name: Install mdBook
      run: cargo install mdbook --vers 0.4.43 --locked
    - name: Build book
      run: cd docs && mdbook build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build
